import { Destination, ServiceItem, PresetItinerary } from './types';

// Let's reference the exact generated images
export const IMAGES = {
  hunza: '/images/hunza-valley-hero.jpg',
  skardu: '/images/skardu-desert.jpg',
  lahore: '/images/lahore-mosque.jpg',
  jeep: '/images/jeep-fairy-meadows.jpg',
  faisalMosque: 'https://images.unsplash.com/photo-1607511874284-bf5072051639?auto=format&fit=crop&q=80&w=1200',
  swat: 'https://images.unsplash.com/photo-1622211910651-344cb8f9d0c6?auto=format&fit=crop&q=80&w=1200',
  gwadar: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&q=80&w=1200',
};

export const SERVICES: ServiceItem[] = [
  {
    id: 'adventure',
    title: 'Adventure Activities',
    description: 'Trekking, camping, rock climbing, paragliding, and white-water rafting in the rugged Karakoram and Hindukush ranges.',
    iconName: 'Compass',
    category: 'Adventure',
  },
  {
    id: 'by-air',
    title: 'By Air Corporate & Family Trips',
    description: 'Premium domestic flight tours to Gilgit, Skardu, and Chitral. Save travel time and experience absolute luxury.',
    iconName: 'Plane',
    category: 'Corporate',
  },
  {
    id: 'corporate-tour',
    title: 'Corporate Tour',
    description: 'Fully-managed corporate retreats, team building, and premium transport/stay coordination for businesses.',
    iconName: 'Briefcase',
    category: 'Corporate',
  },
  {
    id: 'customized-trip',
    title: 'Customised Trip',
    description: 'Tailored travel schedules where you decide the destinations, stay lengths, and vehicle of your choice.',
    iconName: 'Sliders',
    category: 'Custom',
  },
  {
    id: 'customized-plan',
    title: 'Customized Plan',
    description: 'Daily planning assistance, custom route scheduling, and tailored sightseeing guides across Pakistan.',
    iconName: 'Map',
    category: 'Custom',
  },
  {
    id: 'customized-tours',
    title: 'Customized Tours',
    description: 'Curated bespoke tours catering to specific interests like history, photography, or food tours.',
    iconName: 'Sparkles',
    category: 'Custom',
  },
  {
    id: 'day-trip',
    title: 'Day Trip',
    description: 'Short 1-day excursions to historical sites like Taxila, Rohtas Fort, Khanpur Dam, or Murree Hills.',
    iconName: 'CalendarRange',
    category: 'General',
  },
  {
    id: 'home-tours',
    title: 'Home Tours',
    description: 'Domestic homestay-based tours focusing on rural culture, local hospitalities, and peaceful family retreats.',
    iconName: 'Home',
    category: 'Family',
  },
  {
    id: 'hotels-acc',
    title: 'Hotels & Accommodations',
    description: 'Access to exclusive discounted bookings at premium hotels, luxury resorts, glamping sites, and heritage stays.',
    iconName: 'BedDouble',
    category: 'General',
  },
  {
    id: 'jeeps-tour',
    title: 'Jeeps Tour',
    description: 'Challenging off-road 4x4 safaris to Fairy Meadows, Deosai Plains, Shogran, Siri Paye, and remote valleys.',
    iconName: 'Truck',
    category: 'Adventure',
  },
  {
    id: 'tailored-tour',
    title: 'Tailored Tour',
    description: 'Bespoke high-end itineraries matching your specific bucket list, physical pace, and dining preferences.',
    iconName: 'Crown',
    category: 'Custom',
  },
  {
    id: 'tour-plan',
    title: 'Tour Plan',
    description: 'Step-by-step master plan of travel logistics, meal points, driver guides, and daily safety briefs.',
    iconName: 'FileText',
    category: 'General',
  },
  {
    id: 'tours-destinations',
    title: 'Tours Destinations',
    description: 'Curated catalogs of beautiful destinations in Pakistan, from ancient southern deserts to northern peaks.',
    iconName: 'MapPin',
    category: 'General',
  },
];

export const DESTINATIONS: Destination[] = [
  {
    id: 'hunza',
    name: 'Hunza Valley',
    region: 'Gilgit-Baltistan',
    tagline: 'The Shangri-La of Pakistan',
    description: 'Flanked by towering peaks like Rakaposhi and Ladyfinger, Hunza is famous for its blue Attabad Lake, historical Altit/Baltit forts, apricot blossoms, and incredibly hospitable locals.',
    coordinates: { x: 45, y: 15 }, // Adjusted relative position for visual Pakistan Map
    image: IMAGES.hunza,
    highlights: ['Attabad Turquoise Lake', 'Baltit & Altit Forts', 'Hussaini Suspension Bridge', 'Passu Cones Golden Hour', 'Eagle\'s Nest Viewpoint'],
    bestTime: 'April to October',
    defaultItineraryId: 'itinerary-hunza',
  },
  {
    id: 'skardu',
    name: 'Skardu & Baltistan',
    region: 'Gilgit-Baltistan',
    tagline: 'The Gateway to K2',
    description: 'Nestled between the Karakoram giants, Skardu offers cold high-altitude deserts, breathtaking lakes like Shangrila and Sheosar, and the vast wilderness of the Deosai Plains.',
    coordinates: { x: 58, y: 22 },
    image: IMAGES.skardu,
    highlights: ['Katpana Cold Desert Dunes', 'Deosai National Plains', 'Shangrila Resort Resort', 'Sheosar Lake Crossing', 'Shigar Fort Heritage'],
    bestTime: 'June to September',
    defaultItineraryId: 'itinerary-skardu',
  },
  {
    id: 'fairy-meadows',
    name: 'Fairy Meadows & Nanga Parbat',
    region: 'Gilgit-Baltistan',
    tagline: 'The Heaven beneath Nanga Parbat',
    description: 'A legendary green meadow campsite situated at the base of Nanga Parbat, the 9th highest mountain in the world. Reached via a thrilling jeep ride and trek.',
    coordinates: { x: 40, y: 28 },
    image: IMAGES.jeep,
    highlights: ['Thrilling Karakoram Highway Jeep Ride', 'Nanga Parbat Basecamp Trek', 'Pine Forest Camping', 'Reflection Lakes View', 'Bonfire under Milky Way'],
    bestTime: 'June to August',
    defaultItineraryId: 'itinerary-fairy-meadows',
  },
  {
    id: 'swat',
    name: 'Swat Valley',
    region: 'Khyber Pakhtunkhwa',
    tagline: 'The Switzerland of the East',
    description: 'Renowned for its lush green meadows, alpine lakes like Mahodand, gushing rivers, and Buddhist heritage, Swat is a perfect family and adventure destination.',
    coordinates: { x: 28, y: 34 },
    image: IMAGES.swat,
    highlights: ['Mahodand Lake Boating', 'Malam Jabba Ski Resort', 'Kalam Forest Walks', 'Ushu Valley Pine Glades', 'Takht-i-Bahi Archeology'],
    bestTime: 'Year-round (Snow in Winter)',
    defaultItineraryId: 'itinerary-swat',
  },
  {
    id: 'lahore',
    name: 'Lahore Heritage',
    region: 'Punjab',
    tagline: 'The Cultural Heart of Pakistan',
    description: 'A city of magnificent history, food, and culture. From grand Mughal masterpieces like Badshahi Mosque and Lahore Fort to energetic old city food streets.',
    coordinates: { x: 48, y: 56 },
    image: IMAGES.lahore,
    highlights: ['Badshahi Mosque Sunset', 'Shahi Qila (Lahore Fort)', 'Wazir Khan Mosque Mosaics', 'Anarkali & Food Street Feast', 'Wagah Border Ceremony'],
    bestTime: 'October to March',
    defaultItineraryId: 'itinerary-lahore',
  },
  {
    id: 'gwadar',
    name: 'Gwadar & Hingol',
    region: 'Balochistan',
    tagline: 'Where Desert meets the Arabian Sea',
    description: 'An emerging coastal paradise, offering spectacular deep blue waters, golden desert beaches, and the surreal clay rock formations of Hingol National Park.',
    coordinates: { x: 12, y: 88 },
    image: IMAGES.gwadar,
    highlights: ['Hingol Clay Sphinx & Princess of Hope', 'Kund Malir Golden Beach', 'Hammerhead Coastal Cliffs', 'Sunset Marine Drive', 'Boating to Astola Island'],
    bestTime: 'November to February',
    defaultItineraryId: 'itinerary-gwadar',
  },
];

export const PRESET_ITINERARIES: PresetItinerary[] = [
  {
    id: 'itinerary-hunza',
    destinationId: 'hunza',
    title: 'The Golden Hunza Valley Tour',
    durationDays: 5,
    priceEstimate: 'PKR 85,000 / person',
    tourType: 'Customised Trip & Family Tour',
    days: [
      {
        day: 1,
        title: 'Arrival in Islamabad & Drive to Chilas',
        description: 'Meet the team and depart early from Islamabad. Drive along the scenic Karakoram Highway (KKH) or through Babusar Pass. Arrive in Chilas for an overnight stay.',
        activities: ['Scenic drive', 'Sightseeing Babusar Pass', 'Dinner by the Indus River'],
      },
      {
        day: 2,
        title: 'Drive to Hunza & Baltit Fort Sunset',
        description: 'Journey to Karimabad, Hunza. Spot the Three Mountain Ranges Meetpoint (Karakoram, Hindu Kush, Himalayas) and Rakaposhi Viewpoint. Visit Baltit Fort and capture the sunset from Eagle\'s Nest.',
        activities: ['Rakaposhi view', 'Altit/Baltit Fort visit', 'Sunset at Eagle\'s Nest'],
      },
      {
        day: 3,
        title: 'Attabad Lake, Hussaini Bridge & Passu Cones',
        description: 'Explore the spectacular turquoise Attabad Lake. Go boating, cross the thrilling Hussaini Suspension Bridge, and view the majestic Passu Cones.',
        activities: ['Attabad Lake boating', 'Crossing Hussaini Bridge', 'Passu Cones photography'],
      },
      {
        day: 4,
        title: 'Excursion to Khunjerab Pass (Pak-China Border)',
        description: 'Drive to the highest paved international border crossing in the world at 4,693 meters. Witness snow-capped peaks and local wildlife like Ibex in the National Park.',
        activities: ['Khunjerab Pass visit', 'Pak-China border photo', 'Sost bazaar shopping'],
      },
      {
        day: 5,
        title: 'Fly back or return drive to Islamabad',
        description: 'Depart Hunza. Take a return drive back to Islamabad or take the flight option from Gilgit Airport (subject to weather). End of tour.',
        activities: ['Return journey', 'Gilgit airport transit', 'Farewell lunch'],
      },
    ],
  },
  {
    id: 'itinerary-skardu',
    destinationId: 'skardu',
    title: 'Karakoram Kingdoms & Deosai Plains',
    durationDays: 6,
    priceEstimate: 'PKR 110,000 / person',
    tourType: 'By Air Corporate & Family Trip',
    days: [
      {
        day: 1,
        title: 'Fly from Islamabad to Skardu',
        description: 'Catch a scenic flight over the Karakoram giants (Nanga Parbat visible). Land in Skardu, check into your luxury resort. Visit Lower Kachura Lake (Shangrila) and Upper Kachura Lake.',
        activities: ['Scenic flight', 'Shangrila Resort walk', 'Boating on Upper Kachura Lake'],
      },
      {
        day: 2,
        title: 'Shigar Valley & Historic Shigar Fort',
        description: 'Drive to Shigar Valley along the cold desert. Explore Shigar Fort, a beautifully restored 17th-century heritage palace. Hike up to Shigar rock for a panoramic valley view.',
        activities: ['Katpana Desert tour', 'Shigar Fort exploration', 'Organic orchard walks'],
      },
      {
        day: 3,
        title: 'The Great Deosai Plains Expedition',
        description: 'Board a 4x4 Jeep to climb up to Deosai National Park, the second-highest plateau on earth. Look for Himalayan Brown Bears and experience the blue Sheosar Lake.',
        activities: ['Jeep Tour', 'Wildlife spotting', 'Picnic lunch at Sheosar Lake'],
      },
      {
        day: 4,
        title: 'Khaplu Palace & Royal Karakoram Heritage',
        description: 'Drive to Khaplu Valley. Visit the royal Khaplu Palace (now a high-end heritage hotel) and the historic Chaqchan Mosque, a 700-year-old architectural marvel.',
        activities: ['Chaqchan Mosque tour', 'Khaplu Palace tea', 'Local Balti food dining'],
      },
      {
        day: 5,
        title: 'Katpana Desert Safari & Sunset At Sadpara Lake',
        description: 'Enjoy high-speed sand bashing in the Katpana desert. Later, spend a peaceful afternoon visiting Sadpara Lake, the primary water source of Skardu.',
        activities: ['Desert jeep bashing', 'Sadpara Lake visit', 'Skardu traditional market bazaar'],
      },
      {
        day: 6,
        title: 'Return flight to Islamabad',
        description: 'Transfer to Skardu Airport for your return flight to Islamabad, loaded with memories of Baltistan.',
        activities: ['Airport check-in', 'Flight back to Islamabad'],
      },
    ],
  },
  {
    id: 'itinerary-fairy-meadows',
    destinationId: 'fairy-meadows',
    title: 'Nanga Parbat Basecamp Wilderness',
    durationDays: 4,
    priceEstimate: 'PKR 68,000 / person',
    tourType: 'Adventure Activities & Jeeps Tour',
    days: [
      {
        day: 1,
        title: 'Drive Raikot Bridge & Thrilling Jeep Safari',
        description: 'Drive to Raikot Bridge from Chilas or Gilgit. Change to 4x4 local open-top Jeeps for a legendary cliff-side ride to Tato Village, followed by a 3-hour hike up to Fairy Meadows.',
        activities: ['Raikot Jeep ride', 'Trekking through pine forests', 'Sunset view of Nanga Parbat'],
      },
      {
        day: 2,
        title: 'Day Hike to Nanga Parbat Basecamp',
        description: 'Trek through alpine glades and birch woods to Beyal Camp, then proceed to the Nanga Parbat viewpoint and Basecamp (Silberzacken). Touch the glaciers of the Killer Mountain.',
        activities: ['Hiking to Beyal Camp', 'Nanga Parbat basecamp exploration', 'Glacier crossing'],
      },
      {
        day: 3,
        title: 'Meadow Leisure, Reflection Lakes & Camping',
        description: 'Spend a leisurely day relaxing in the grassy meadows. Capture reflection shots of Nanga Parbat in the pristine alpine ponds. Evening BBQ and folk bonfire.',
        activities: ['Photography', 'Horse riding', 'Folk music bonfire and BBQ'],
      },
      {
        day: 4,
        title: 'Hike Down to Tato & Drive to Islamabad',
        description: 'Hike back down to Tato Village, board the Jeeps to Raikot Bridge, and continue your journey back towards Islamabad.',
        activities: ['Descent trek', 'Jeep ride back', 'Drive along Indus river'],
      },
    ],
  },
  {
    id: 'itinerary-swat',
    destinationId: 'swat',
    title: 'Emerald Swat & Kalam Forest Escapade',
    durationDays: 4,
    priceEstimate: 'PKR 62,000 / person',
    tourType: 'Family Trip & Customized Plan',
    days: [
      {
        day: 1,
        title: 'Islamabad to Kalam Valley via Swat Motorway',
        description: 'Drive from Islamabad on the ultra-modern Swat Motorway. Stop at Riverside Fizz points. Pass Mingora and drive up to Kalam Valley, along the Swat River.',
        activities: ['Motorway cruise', 'Swat River side stops', 'Kalam evening stroll'],
      },
      {
        day: 2,
        title: 'Ushu Forest & Mahodand Lake Exploration',
        description: 'Board local 4x4 vehicles. Drive through the dense, tall pine trees of Ushu Forest. Spot the Matiltan Waterfall and reach the pristine Mahodand Lake for boating.',
        activities: ['Ushu Forest walk', 'Matiltan Waterfall', 'Mahodand Lake boating & trout lunch'],
      },
      {
        day: 3,
        title: 'Malam Jabba Ski Resort chairlift ride',
        description: 'Drive down to Malam Jabba, the premier hill station and ski resort in Swat. Take the scenic chairlift ride, zip-line, and enjoy panoramic views of the Hindu Kush.',
        activities: ['Malam Jabba chairlift', 'Ziplining adventure', 'Mountain resort stay'],
      },
      {
        day: 4,
        title: 'White Palace & Return to Islamabad',
        description: 'Visit the historic White Palace in Marghazar, built of white marble. Afterward, start your return journey back to Islamabad.',
        activities: ['White Palace visit', 'Sufi shrine view', 'Return drive to Islamabad'],
      },
    ],
  },
  {
    id: 'itinerary-lahore',
    destinationId: 'lahore',
    title: 'Mughal Majesty Cultural Tour',
    durationDays: 2,
    priceEstimate: 'PKR 25,000 / person',
    tourType: 'Day Trip & Home Tours',
    days: [
      {
        day: 1,
        title: 'Walled City Walk & Wazir Khan Mosaic Art',
        description: 'Enter Delhi Gate and explore the vibrant narrow streets of old Lahore. Visit Shahi Hammam and admire the unmatched tile work of Wazir Khan Mosque. Experience an authentic Lahore Food Street feast.',
        activities: ['Old City guided walk', 'Wazir Khan Mosque tour', 'Mouthwatering traditional dinner'],
      },
      {
        day: 2,
        title: 'Lahore Fort, Badshahi Mosque & Wagah Border',
        description: 'Tour the sprawling Lahore Fort, Sheesh Mahal, and the iconic Badshahi Mosque. In the afternoon, head to the Wagah Border to witness the roaring military parade ceremony.',
        activities: ['Lahore Fort history', 'Badshahi Mosque view', 'Wagah Border flag lowering ceremony'],
      },
    ],
  },
  {
    id: 'itinerary-gwadar',
    destinationId: 'gwadar',
    title: 'Southern Coastal Sands Hingol & Gwadar',
    durationDays: 3,
    priceEstimate: 'PKR 55,000 / person',
    tourType: 'Corporate Tour & Customised Trip',
    days: [
      {
        day: 1,
        title: 'Makran Coastal Highway Drive & Hingol Sphinx',
        description: 'Drive from Karachi along the world-renowned Makran Coastal Highway. Marvel at the unique rock formations in Hingol National Park, including the natural Sphinx and the Princess of Hope. Overnight at Kund Malir Beach camp.',
        activities: ['Coastal highway cruise', 'Hingol clay sculptures tour', 'Beach camping and stargazing'],
      },
      {
        day: 2,
        title: 'Drive to Gwadar & Marine Drive Sunset',
        description: 'Drive further west to the deep-sea port city of Gwadar. Walk along the sweeping Marine Drive, and ascend Koh-e-Batil hammerhead cliff for a breath-taking sunset over the Arabian Sea.',
        activities: ['Scenic coastal drive', 'Koh-e-Batil sunset hike', 'Local Baloch seafood dinner'],
      },
      {
        day: 3,
        title: 'Gwadar Fish Market & Astola Island Boat Cruise',
        description: 'Visit the buzzing, traditional Gwadar Port Fish Market. Take a brief morning speed boat ride out to explore the pristine golden sands, then begin your return drive to Karachi.',
        activities: ['Fish harbor auction', 'Speedboat ride', 'Return drive along the ocean'],
      },
    ],
  },
];

