import { initializeApp } from "firebase/app";
import { initializeFirestore, doc, getDocFromServer } from "firebase/firestore";
import { getAuth } from "firebase/auth";

// Import configuration generated by the system, with a fallback to the user's configuration
import firebaseConfig from "../firebase-applet-config.json";

// User's explicit configuration overrides or fallback
const finalConfig = {
  apiKey: firebaseConfig.apiKey || "AIzaSyCPQAJvjQx6xNLU7WLlaLiRIqs07X759vU",
  authDomain: firebaseConfig.authDomain || "trodden-travelers.firebaseapp.com",
  projectId: firebaseConfig.projectId || "trodden-travelers",
  storageBucket: firebaseConfig.storageBucket || "trodden-travelers.firebasestorage.app",
  messagingSenderId: firebaseConfig.messagingSenderId || "685460436235",
  appId: firebaseConfig.appId || firebaseConfig.appId || "1:685460436235:web:a957d4838b41727f971e0e",
};

const app = initializeApp(finalConfig);

// Using the correct firestore database ID (important for AI Studio Firestore routing)
// Enforcing long-polling to prevent connection stalling/timeouts in sandboxed environments
export const db = initializeFirestore(app, {
  experimentalForceLongPolling: true,
}, (firebaseConfig as any).firestoreDatabaseId || "(default)");

export const auth = getAuth(app);

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
    providerInfo?: {
      providerId?: string | null;
      email?: string | null;
    }[];
  }
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth.currentUser?.uid,
      email: auth.currentUser?.email,
      emailVerified: auth.currentUser?.emailVerified,
      isAnonymous: auth.currentUser?.isAnonymous,
      tenantId: auth.currentUser?.tenantId,
      providerInfo: auth.currentUser?.providerData?.map(provider => ({
        providerId: provider.providerId,
        email: provider.email,
      })) || []
    },
    operationType,
    path
  }
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

async function testConnection() {
  try {
    await getDocFromServer(doc(db, 'test', 'connection'));
  } catch (error) {
    if(error instanceof Error && error.message.includes('the client is offline')) {
      console.error("Please check your Firebase configuration.");
    }
  }
}
testConnection();

export default app;
